# amount of locks to fetch per loop - fewer locks than this will be displayed
# as some will be filtered out. max: 100
# default: 15
amount_to_fetch = 15

# show the keyholder's name at the end of the lock. will require more terminal width.
# default: true
show_keyholder_names = true

[formatting]

# remove emojis from lock title and description as they mess with the table in some terminals
# some other unicode symbols also mess it up, to remove everything see option below
# default: true
remove_emojis = true

# nuclear option: enforce ascii; your grid will 100% be aligned
# this will remove various letters and symbols, but anything english should be alright
# default: false
enforce_ascii = false

# columns: max time, needs password, title, description, description length, link, keyholder_name

# minimum column widths - best to leave alone unless you know what you're doing
# default: [5, 1, 4, 8, 5, 52, 20]
min_widths = [5, 1, 4, 8, 5, 52, 20]

# defines column widths flexibility - best to leave alone unless you know what you're doing
# a number denotes the weight of that column when assigning free space
# default: [0, 0, 1, 3, 0, 0, 0]
flexibility = [0, 0, 1, 3, 0, 0, 0]

[criteria]

# minimum characters in lock description for lock to be displayed TODO removes umlaute
# default: 10
minimum_description_length = 10

# show locks with findom keyholders?
# default: false
show_findom = false

# the largest maximum time (in seconds) to display, locks above will be hidden. set to 0 for 'no max time'
# default: 0
max_max_time = 0

[criteria.links]
# this table aims to remove locks created just to advertise shared links

# show locks that include links to chaster in the title?
# default: false
show_linked_titles = false

# same as above, but applies to the description
# default: false
show_linked_descriptions = false

# show locks with description that start with a link to chaster?
# default: 
show_desc_startswith_link = false

[criteria.blacklists]

# array of blacklisted usernames, their locks will be hidden automatically, not case sensitive
# default: []
users = []

# array of blacklisted words in lock title or description; locks with these words will not be shown, not case sensitive
# consider that this can't check if the word is listed under 'limits' or similar but just blanket removes the lock
# default: []
keywords = []

# keyholder genders to remove, not case sensitive
# you can enter other values if you want but they are user-given so spelling / spacing is unclear
# options: "Male", "Female", "" # "" is for unspecified gender
# default: []
keyholder_genders = []
