# amount of locks to fetch per loop - fewer locks than this will be displayed
# as some will be filtered out. max: 100
# default: 15
amount_to_fetch = 15

# show the keyholder's name at the end of the lock. will require more terminal width.
# default: true
show_keyholder_names = true

# list of strings, each string representing a column
# all strings must be available as a 'name' property of a table under [columns]
# default: ["maxtime", "password_needed", "name", "description", "description_len", "link", "keyholder_name"]
columns = ["maxtime", "password_needed", "name", "description", "description_len", "link", "keyholder_name"]

[formatting]

# remove emojis from lock title and description as they mess with the table in some terminals
# some other unicode symbols also mess it up, to remove everything see option below
# default: true
remove_emojis = true

# nuclear option: enforce ascii; your grid will 100% be aligned
# this will remove various letters and symbols, but anything english should be alright
# default: false
enforce_ascii = false

[criteria]

# minimum characters in lock description for lock to be displayed TODO removes umlaute
# default: 10
minimum_description_length = 10

# show locks with findom keyholders?
# default: false
show_findom = false

# the largest maximum time (in seconds) to display, locks above will be hidden. set to 0 for 'no max time'
# default: 0
max_max_time = 0

[criteria.links]
# this table aims to remove locks created just to advertise shared links

# show locks that include links to chaster in the title?
# default: false
show_linked_titles = false

# same as above, but applies to the description
# default: false
show_linked_descriptions = false

# show locks with description that start with a link to chaster?
# default: false
show_desc_startswith_link = false

[criteria.blacklists]

# array of blacklisted usernames, their locks will be hidden automatically, not case sensitive
# default: []
users = []

# array of blacklisted words in lock title or description; locks with these words will not be shown, not case sensitive
# consider that this can't check if the word is listed under 'limits' or similar but just blanket removes the lock
# default: []
keywords = []

# keyholder genders to remove, not case sensitive
# you can enter other values if you want but they are user-given so spelling / spacing is unclear
# options: "Male", "Female", "" # "" is for unspecified gender
# default: []
keyholder_genders = []

[available_columns]
# available columns below
# the flexibility value represents the weight of that column when allocating free terminal space
# the max_width values tend to be reasonable, but do increase if needed; 0 means no max

[available_columns.maxtime]
name        = "maxtime"
min_width   = 5         # default 5
flexibility = 0         # default 0
max_width   = 6         # default 6

[available_columns.password_needed]
name        = "password_needed"
min_width   = 1                 # default 1
flexibility = 0                 # default 0
max_width   = 1                 # default 1

[available_columns.name]
name        = "name"
min_width   = 5      # default 5
flexibility = 1      # default 1
max_width   = 60     # default 60; limit from chaster

[available_columns.description]
name        = "description"
min_width   = 5             # default 5
flexibility = 3             # default 3
max_width   = 0             # default 0

[available_columns.description_len]
name        = "description_len"
min_width   = 5                 # default 5
flexibility = 0                 # default 0
max_width   = 6                 # default 6

[available_columns.link]
name        = "link"
min_width   = 52     # default 52
flexibility = 0      # default 0
max_width   = 52     # default 52

[available_columns.keyholder_name]
name        = "keyholder_name"
min_width   = 10               # default 10
flexibility = 0.4              # default 0.4
max_width   = 20               # default 20; limit from chaster

[available_columns.keyholder_gender]
name        = "keyholder_gender"
min_width   = 6                  # default 6
flexibility = 0.3                # default 0.3
max_width   = 0                  # default 0
